### ISSUE TITLE
[Translations] A spelling mistake in readme.txt

### ISSUE THREAD

**Issue by FlyingStarlight** [OnePlusOSS/android_vendor_qcom_opensource_audio_kernel_sm8150#1]
Line 1
`... is work normal, pelase help add ...
`
The correct spelling of **pelase**  is "p**lea**se"

**Comment by hecaiqiang** [comment]
Ok, got it, thanks very much.

**Comment by aaronqiuchiu** [comment]
https://github.com/OnePlusOSS/android_vendor_qcom_opensource_audio_kernel_sm8150/commit/db560235a67272ddcd55a4ba12d22637a440ce95
